//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        //  All dimensions are in decimal and relative to frame size (not in pixels).
        public float x;
        public float y;
        public float w;
        public float h;
        public float conf;
        public ushort label_id;
        public string label_name;

        public BoundingBoxMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.w = 0.0f;
            this.h = 0.0f;
            this.conf = 0.0f;
            this.label_id = 0;
            this.label_name = "";
        }

        public BoundingBoxMsg(float x, float y, float w, float h, float conf, ushort label_id, string label_name)
        {
            this.x = x;
            this.y = y;
            this.w = w;
            this.h = h;
            this.conf = conf;
            this.label_id = label_id;
            this.label_name = label_name;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.w);
            deserializer.Read(out this.h);
            deserializer.Read(out this.conf);
            deserializer.Read(out this.label_id);
            deserializer.Read(out this.label_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.w);
            serializer.Write(this.h);
            serializer.Write(this.conf);
            serializer.Write(this.label_id);
            serializer.Write(this.label_name);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nw: " + w.ToString() +
            "\nh: " + h.ToString() +
            "\nconf: " + conf.ToString() +
            "\nlabel_id: " + label_id.ToString() +
            "\nlabel_name: " + label_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
