//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class BoundingBoxArrayMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/BoundingBoxArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public BoundingBoxMsg[] bounding_boxes;

        public BoundingBoxArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.bounding_boxes = new BoundingBoxMsg[0];
        }

        public BoundingBoxArrayMsg(Std.HeaderMsg header, BoundingBoxMsg[] bounding_boxes)
        {
            this.header = header;
            this.bounding_boxes = bounding_boxes;
        }

        public static BoundingBoxArrayMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxArrayMsg(deserializer);

        private BoundingBoxArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.bounding_boxes, BoundingBoxMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.bounding_boxes);
            serializer.Write(this.bounding_boxes);
        }

        public override string ToString()
        {
            return "BoundingBoxArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nbounding_boxes: " + System.String.Join(", ", bounding_boxes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
